### ISSUE TITLE
Question: Göweil DLC

### ISSUE THREAD

**Issue by MeRida2104** [Timmeey86/FS25_UnloadBalesEarly#3]
Hi, thank you for your mod :) It works great, but does it already support the Göweil DLC? We're using it on our dedicated server, but as soon as the Göweil Vario Master has baled a (150er) bale, it stops at 14499 L and doesn't bale any further. This behavior doesn't occur in singleplayer, only in multiplayer (whether hosted MP or dedicated MP).

Could you please take a look at this?

Best regards,
MeRida

**Comment by Morgosnod** [comment]
I was just about to write the same, but in my case it is also in singleplayer.
I had a look at the code and discovered that the Göweil Vario Master is considered to be a 2 chamber baler. As a consequence it does only overload, if the container is completely full. When I commented out the code regarding 2 chamber balers it worked again. Maybe this information helps you, because I also would like that to be fixed.

Best regards,
Morgosnod

**Comment by Timmeey86** [comment]
Alright, I'll have a look at this. Hoping to be able to reproduce it in single player since I currently don't have a server for testing

**Comment by Timmeey86** [comment]
Found the issue: The Göweil baler always automatically starts overloading while the other two-chamber balers only do so when full. The Göweil Vario Master starts overloading as soon as anything is in the first chamber, and I reset the threshold to 100% when unloading started, rather than the original overloading threshold (0% in this case).

I fixed it and also prevent the "overload to second chamber" option from being shown for balers like these since that would be pointless.

@MeRida2104 @Morgosnod @alfi0212
Here's the new release: https://github.com/Timmeey86/FS22_UnloadBalesEarly/releases/tag/v1.0.0.1

The issue was pretty obvious so I'm confident the fix will work in multiplayer as well.
